### ISSUE TITLE
error: unable to write to pipe (Broken pipe)

### ISSUE THREAD

**Issue by YoinkerBoinker** [dracutdevs/dracut#2628]
**Describe the bug**
When updating the System with `pacman -Syu `or `yay` sometimes you'd get "error: unable to write to pipe (Broken pipe)". I can't make sense of it and don't know what's causing it though i saw this popping up in the EndeavourOS Forums a few times and also experienced it on Arch. Running dracut again right after will not bring up the error again. It shouldn't be a space Error since i have 1GB Space for /efi and only one Kernel/Fallback installed.  For example my current drive looks like
`/dev/nvme1n1p1  999M    101M  898M   11% /efi`

**Distribution used**
have seen this on both Arch and EndeouverOS and on different systems  (one is an Intel/NV system the other a Pure AMD System)

**Dracut version**
059-5

**Init system**
Systemd

**To Reproduce**
just update the system using for example yay or pacman -Syu (today is a good day. To do so when using EndeavourOS happend on both my Systems)

**Expected behavior**
shouldn't happen

**Additional context**
It'S actually not clear what's the cause of it. It could be visible only since it happens right after creating the Initrd
the Error will look like
```
"dracut: *** Creating initramfs image file '/efi/XXXXXX/6.7.5-arch1-1/initrd' done ***
error: unable to write to pipe (Broken pipe)"
```
in case it helps these were the packages that got upgrades
```
[2024-02-21T15:00:45+0100] [ALPM] upgraded dav1d (1.3.0-1 -> 1.4.0-1)
[2024-02-21T15:00:45+0100] [ALPM] upgraded libffi (3.4.5-1 -> 3.4.6-1)
[2024-02-21T15:00:45+0100] [ALPM] upgraded libvpl (2.10.1-1 -> 2.10.2-1)
[2024-02-21T15:00:45+0100] [ALPM] upgraded giflib (5.2.1-2 -> 5.2.2-1)
[2024-02-21T15:00:45+0100] [ALPM] upgraded highway (1.0.7-1 -> 1.1.0-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded firefox (122.0.1-1 -> 123.0-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded firefox-i18n-de (122.0.1-1 -> 123.0-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded ijs (0.35-5 -> 0.35-6)
[2024-02-21T15:00:46+0100] [ALPM] upgraded jasper (4.2.0-1 -> 4.2.1-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded lib32-libffi (3.4.5-1 -> 3.4.6-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded libaio (0.3.113-2 -> 0.3.113-3)
[2024-02-21T15:00:46+0100] [ALPM] upgraded linux-firmware-whence (20240115.9b6d0b08-2 -> 20240220.97b693d2-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded linux-firmware (20240115.9b6d0b08-2 -> 20240220.97b693d2-1)
[2024-02-21T15:00:46+0100] [ALPM] upgraded openssh (9.6p1-1 -> 9.6p1-3)
[2024-02-21T15:00:46+0100] [ALPM] upgraded qca-qt5 (2.3.8-1 -> 2.3.8-2)
[2024-02-21T15:00:46+0100] [ALPM] upgraded xterm (389-1 -> 390-1)
```

**Comment by davidhaley** [comment]
Same.

Version: `dracut 059`

```
...
dracut: *** Stripping files done ***
dracut: *** Creating image file '/efi/ab0e96c35931426ebfc1f4848674580c/6.6.17-1-lts/initrd' ***
dracut: *** Creating initramfs image file '/efi/ab0e96c35931426ebfc1f4848674580c/6.6.17-1-lts/initrd' done ***
error: unable to write to pipe (Broken pipe)
(13/26) Backing up /boot...
...
```

**Comment by 100busy** [comment]
i am also having this same issue. i tried with darcut-git but same result
happening for me with linux-firmware which i saw in @YoinkerBoinker list of packages

**Comment by yogo1212** [comment]
Hi :-)

Could it be that this has nothing to do with dracut itself but with pacman/libalpm?
I noticed that STDIN is flushed between runs - maybe STDOUT/STDERR are also closed.
I know for certain that this is something that has changed recently in libalpm/pacman because I used to be able to queue multiple yay/pacman invocations by typing them after the prompt and that no longer works.

**Comment by notpeelz** [comment]
Not stale. Recently ran into this issue. Would be good to figure out if pacman/libalpm is to blame, or if the issue is on the side of Dracut.

**Comment by FlareFlo** [comment]
I regularly get this every 5th system update

**Comment by notpeelz** [comment]
Have you been able to reproduce it on demand? I tried reinstalling e.g. linux-firmware a few times in a row but couldn't get it to trigger again. That makes it a bit of a pain to debug...

**Comment by FlareFlo** [comment]
It seems to be completely random, happening both on my desktop and laptop system. The worst part about this is that, when I miss the error message (which neither pacman or paru seem to care for) and reboot the system, I will have to recover the initramfs via a recovery stick as the folder on the efi partition is empty

**Comment by notpeelz** [comment]
Oh yikes. I assumed it was benign. I've been running dracut manually every time I encountered the error (out of caution). Good to know.

**Comment by FlareFlo** [comment]
> Oh yikes. I assumed it was benign. I've been running dracut manually every time I encountered the error (out of caution). Good to know.

I always have to run `reinstall-kernels`(from endeavourOS) when i encounter the error in the output, which always works out fine.

**Comment by FlareFlo** [comment]
> > Oh yikes. I assumed it was benign. I've been running dracut manually every time I encountered the error (out of caution). Good to know.
> 
> I always have to run `reinstall-kernels`(from endeavourOS) when i encounter the error in the output, which always works out fine.

I should add that, running the script (and with it dracut) manually never printed that error, and i easily had to do this in excess of 30 times

**Comment by notpeelz** [comment]
Not stale

**Comment by Gotoro** [comment]
This is not a stale issue. I've been having this problem repeatedly on my work machine running endeavouros and my laptop too. I haven't had any problems regarding boot issues though, seems purely cosmetic from my viewpoint.
```log

(15/29) Running kernel-install...
Running kernel-install for 6.17.8-arch1-1
dracut[I]: Executing: /usr/bin/dracut --no-hostonly --force /efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd-fallback 6.17.8-arch1-1
dracut[I]: *** Including module: bash ***
dracut[I]: *** Including module: systemd ***
dracut[I]: *** Including module: systemd-ask-password ***
dracut[I]: *** Including module: systemd-battery-check ***
dracut[I]: *** Including module: systemd-cryptsetup ***
dracut[I]: *** Including module: systemd-initrd ***
dracut[I]: *** Including module: systemd-journald ***
dracut[I]: *** Including module: systemd-modules-load ***
dracut[I]: *** Including module: systemd-pcrphase ***
dracut[I]: *** Including module: systemd-sysctl ***
dracut[I]: *** Including module: systemd-tmpfiles ***
dracut[I]: *** Including module: systemd-udevd ***
dracut[I]: *** Including module: modsign ***
dracut[I]: *** Including module: i18n ***
dracut[I]: *** Including module: systemd-sysusers ***
dracut[I]: *** Including module: btrfs ***
dracut[I]: *** Including module: crypt ***
dracut[I]: *** Including module: dm ***
dracut[I]: *** Including module: fs-lib ***
dracut[I]: *** Including module: kernel-modules ***
dracut[I]: *** Including module: kernel-modules-extra ***
dracut[I]: *** Including module: lvm ***
dracut[I]: *** Including module: mdraid ***
dracut[I]: *** Including module: nvdimm ***
dracut[I]: *** Including module: qemu ***
dracut[I]: *** Including module: qemu-net ***
dracut[I]: *** Including module: fido2 ***
dracut[I]: *** Including module: pkcs11 ***
dracut[I]: *** Including module: hwdb ***
dracut[I]: *** Including module: lunmask ***
dracut[I]: *** Including module: resume ***
dracut[I]: *** Including module: rootfs-block ***
dracut[I]: *** Including module: terminfo ***
dracut[I]: *** Including module: udev-rules ***
dracut[I]: *** Including module: virtiofs ***
dracut[I]: *** Including module: dracut-systemd ***
dracut[I]: *** Including module: initqueue ***
dracut[I]: *** Including module: usrmount ***
dracut[I]: *** Including module: base ***
dracut[I]: *** Including module: shell-interpreter ***
dracut[I]: *** Including module: shutdown ***
dracut[I]: *** Including modules done ***
dracut[I]: *** Installing kernel module dependencies ***
dracut[I]: *** Installing kernel module dependencies done ***
dracut[I]: *** Resolving executable dependencies ***
dracut[I]: *** Resolving executable dependencies done ***
dracut[I]: *** Generating early-microcode cpio image ***
dracut[I]: *** Constructing AuthenticAMD.bin ***
dracut[I]: *** Store current command line parameters ***
dracut[I]: *** Stripping files ***
dracut[I]: *** Stripping files done ***
dracut[I]: *** Creating image file '/efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd-fallback' ***
dracut[I]: *** Hardlinking files ***
dracut[I]: *** Hardlinking files done ***
dracut[I]: *** Creating initramfs image file '/efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd-fallback' done ***
dracut[I]: Executing: /usr/bin/dracut --hostonly --no-hostonly-cmdline -f /efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd 6.17.8-arch1-1
dracut[I]: *** Including module: bash ***
dracut[I]: *** Including module: systemd ***
dracut[I]: *** Including module: systemd-ask-password ***
dracut[I]: *** Including module: systemd-battery-check ***
dracut[I]: *** Including module: systemd-cryptsetup ***
dracut[I]: *** Including module: systemd-initrd ***
dracut[I]: *** Including module: systemd-journald ***
dracut[I]: *** Including module: systemd-modules-load ***
dracut[I]: *** Including module: systemd-pcrphase ***
dracut[I]: *** Including module: systemd-sysctl ***
dracut[I]: *** Including module: systemd-tmpfiles ***
dracut[I]: *** Including module: systemd-udevd ***
dracut[I]: *** Including module: i18n ***
dracut[I]: *** Including module: systemd-sysusers ***
dracut[I]: *** Including module: btrfs ***
dracut[I]: *** Including module: crypt ***
dracut[I]: *** Including module: dm ***
dracut[I]: *** Including module: fs-lib ***
dracut[I]: *** Including module: kernel-modules ***
dracut[I]: *** Including module: kernel-modules-extra ***
dracut[I]: *** Including module: lvm ***
dracut[I]: *** Including module: mdraid ***
dracut[I]: *** Including module: qemu ***
dracut[I]: *** Including module: qemu-net ***
dracut[I]: *** Including module: hwdb ***
dracut[I]: *** Including module: lunmask ***
dracut[I]: *** Including module: resume ***
dracut[I]: *** Including module: rootfs-block ***
dracut[I]: *** Including module: terminfo ***
dracut[I]: *** Including module: udev-rules ***
dracut[I]: *** Including module: virtiofs ***
dracut[I]: *** Including module: dracut-systemd ***
dracut[I]: *** Including module: initqueue ***
dracut[I]: *** Including module: usrmount ***
dracut[I]: *** Including module: base ***
dracut[I]: *** Including module: shell-interpreter ***
dracut[I]: *** Including module: shutdown ***
dracut[I]: *** Including modules done ***
dracut[I]: *** Installing kernel module dependencies ***
dracut[I]: *** Installing kernel module dependencies done ***
dracut[I]: *** Resolving executable dependencies ***
dracut[I]: *** Resolving executable dependencies done ***
dracut[I]: *** Generating early-microcode cpio image ***
dracut[I]: *** Constructing AuthenticAMD.bin ***
dracut[I]: *** Store current command line parameters ***
dracut[I]: *** Stripping files ***
dracut[I]: *** Stripping files done ***
dracut[I]: *** Creating image file '/efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd' ***
dracut[I]: *** Hardlinking files ***
dracut[I]: *** Hardlinking files done ***
dracut[I]: *** Creating initramfs image file '/efi/81183a8db0b644f7adc3e93374b2f03f/6.17.8-arch1-1/initrd' done ***
error: unable to write to pipe (Broken pipe)
```

**Comment by yogo1212** [comment]
anyone in here who isn't using arch and only invokes dracut through pacman/libalpm?
maybe we should take it to the arch bug tracker.

**Comment by Gotoro** [comment]
> anyone in here who isn't using arch and only invokes dracut through pacman/libalpm? maybe we should take it to the arch bug tracker.

Not using arch *and* using pacman?

**Comment by yogo1212** [comment]
yeah, that was badly worded 🙈

please raise your hands if you get the "broken pipe" error without pacman, yay, or so involved (e.g. you invoke dracut manually or through other infrastructure/another package manager).

my assumption is that this issue has to do with how dracut is invoked by libalpm.

if nobody here says they are NOT using arch/libalpm (-> everybody here uses pacman/arch/libalpm), we can probably close this issue and open a bug over at arch's bug tracker/pacman mailing list or so.

**Comment by Gotoro** [comment]
I've created a small demonstration as to how to reproduce this. The bug happens at the script `/usr/share/libalpm/scripts/kernel-install-hook`, namely at the `break` point of the first if stament:
```bash
   3 │ while read -r line; do
   4 │     if [[ $line != */vmlinuz ]]; then
   5 │         # this means this is something other than a kernel change
   6 │         all=1
   7 │         break # <<<---------- HERE
   8 │     fi
```

First of all, we need a script that mimics the behaviour of the `libalpm` script, as @yogo1212  pointed out.
Put it at `/tmp/break_test.sh`
```bash
#!/bin/bash

while read -r line; do
    # If the file is not a vmlinuz, we break the loop and exit.
    if [[ $line != */vmlinuz ]]; then
        echo ":: [TEST] Found non-kernel file ($line). Breaking now..."
        break
    fi
    echo ":: [TEST] Processing $line"
done
```

and the accompanying pacman hook `99-broken-pipe-test.hook`, which you should put at `/usr/share/libalpm/hooks/99-broken-pipe-test.hook`
```hook
[Trigger]
Operation = Install
Operation = Upgrade
Type = Path
Target = usr/*

[Action]
Description = Testing Broken Pipe Error
When = PostTransaction
Exec = /tmp/break_test.sh
NeedsTargets
```

Then we trigger the bug by reinstalling a "big" package, which provides lots of files, as the "small" package simply won't write enough of data into the pipe.
```bash
➜  hooks pacman -Ql | cut -d' ' -f1 | uniq -c | sort -n | tail
   5127 qt6-declarative
   6519 foomatic-db
   6729 openssl
   6865 foomatic-db-ppds
   7101 plasma-workspace
   7581 linux
  12540 libreoffice-fresh
  21180 linux-headers
  39917 breeze-icons
  46667 eos-qogir-icons
```

I've went with `breeze-icons` as it's enough:
```text
➜  hooks sudo pacman -S breeze-icons
warning: breeze-icons-6.20.0-1 is up to date -- reinstalling
resolving dependencies...
looking for conflicting packages...

Package (1)         Old Version  New Version  Net Change

extra/breeze-icons  6.20.0-1     6.20.0-1       0,00 MiB

Total Installed Size:  82,70 MiB
Net Upgrade Size:       0,00 MiB

:: Proceed with installation? [Y/n]
(1/1) checking keys in keyring                                                                                                  [------------------------------------------------------------------------------] 100%
(1/1) checking package integrity                                                                                                [------------------------------------------------------------------------------] 100%
(1/1) loading package files                                                                                                     [------------------------------------------------------------------------------] 100%
(1/1) checking for file conflicts                                                                                               [------------------------------------------------------------------------------] 100%
:: Processing package changes...
(1/1) reinstalling breeze-icons                                                                                                 [------------------------------------------------------------------------------] 100%
:: Running post-transaction hooks...
(1/4) Arming ConditionNeedsUpdate...
(2/4) Testing Broken Pipe Error
:: [TEST] Found non-kernel file (usr/). Breaking now...
error: unable to write to pipe (Broken pipe)
(3/4) Updating icon theme caches...
(4/4) Checking which packages need to be rebuilt
➜  hooks
```
and with this we actually get the pacman induced (I assume at least) specific error. The error is highlighted with red, definitely not part of my script so probably truly pacman related

<img width="506" height="60" alt="Image" src="https://github.com/user-attachments/assets/48a1c46c-930f-499d-b9e2-4d992081bebb" />

# Solution?
**I'm assuming by changing `break` to `continue` we can actually mitigate this.**

But also, it is truly not a problem with `dracut` it seems. Perhaps somebody can point me in the right direction of finding the author?

The file is provided by `kernel-install-for-dracut` package, by `manuel <manuel at endeavouros.com>` and is packaged to the `endeavouros/kernel-install-for-dracut` repository.

```text
➜  ~ pacman -Qo /usr/share/libalpm/hooks/90-kernel-install.hook
/usr/share/libalpm/hooks/90-kernel-install.hook is owned by kernel-install-for-dracut 1.13-1
➜  ~ pacman -Qi kernel-install-for-dracut
Name            : kernel-install-for-dracut
Version         : 1.13-1
Description     : Enables systemd-boot automation using kernel-install with dracut
Architecture    : any
URL             : https://gitlab.com/dalto.8/kernel-install-for-dracut
Licenses        : GPL2
Groups          : None
Provides        : None
Depends On      : dracut
Optional Deps   : None
Required By     : None
Optional For    : None
Conflicts With  : mkinitcpio  kernel-install-mkinitcpio
Replaces        : None
Installed Size  : 20,80 KiB
Packager        : manuel <manuel@endeavouros.com>
Build Date      : Ср 04 июн 2025 17:56:32
Install Date    : Чт 16 окт 2025 16:02:09
Install Reason  : Explicitly installed
Install Script  : No
Validated By    : Signature

➜  ~ pacman -Ss kernel-install-for-dracut
endeavouros/kernel-install-for-dracut 1.13-1 [installed]
    Enables systemd-boot automation using kernel-install with dracut
➜  ~
```

**Comment by yogo1212** [comment]
that is excellent work! ❤️ 

i believe this is the base package used by arch and endeavouros:
https://gitlab.com/dalto.8/kernel-install-for-dracut

technically, it's a [regress](https://gitlab.com/dalto.8/kernel-install-for-dracut/-/commit/58ec58e6fbf1e16b84b7a60fd0dd7dfcef71628c).

do you want to create a patch for them?
i doubt they would want to re-add the continue. perhaps a `cat >/dev/null &` right before the `break`?
maybe even `cat >/dev/null &`?

**Comment by SinTan1729** [comment]
> Perhaps somebody can point me in the right direction of finding the author?

I think it's @manuel-192 on GH.

**Comment by Gotoro** [comment]
> that is excellent work! ❤️
> 
> i believe this is the base package used by arch and endeavouros: https://gitlab.com/dalto.8/kernel-install-for-dracut
> 
> technically, it's a [regress](https://gitlab.com/dalto.8/kernel-install-for-dracut/-/commit/58ec58e6fbf1e16b84b7a60fd0dd7dfcef71628c).
> 
> do you want to create a patch for them? i doubt they would want to re-add the continue. perhaps a `cat >/dev/null &` right before the `break`? maybe even `cat >/dev/null &`?

Thank you! I'd like to contribute, but I'm afraid I don't fully understand the nature of the bug, even though I've determined where the bug happens. So I can't really comment on the viability of the proposed solution. I see gitlab has issues too, so perhaps I'd redirect the issue there, cheers for finding the author!

**Comment by Gotoro** [comment]
[What's said is done](https://gitlab.com/dalto.8/kernel-install-for-dracut/-/issues/5)

This is not an issue with `dracut`, but perhaps it would be good to leave this as open until the maintainer has solved the problem?

**Comment by CaptainCoward** [comment]
I'm sorry if this is a stupid question but maybe someone knows the answer: Do you actually need to "reinistall-kernels" after this happens? Or is this just visual? I usually do run it whenever the broken pipe problem appears  to be on the "safe" side. But it seems to also work fine without it? Anyone has a clue?

**Comment by MartinX3** [comment]
I compared the file sizes.  
When it happens and I then reinstall the kernel the resulting file is bigger.

**Comment by Gotoro** [comment]
> I'm sorry if this is a stupid question but maybe someone knows the answer: Do you actually need to "reinistall-kernels" after this happens? Or is this just visual? I usually do run it whenever the broken pipe problem appears to be on the "safe" side. But it seems to also work fine without it? Anyone has a clue?

I don't ever do this. Works fine for me even without force reinstalling

**Comment by FlareFlo** [comment]
> I'm sorry if this is a stupid question but maybe someone knows the answer: Do you actually need to "reinistall-kernels" after this happens? Or is this just visual? I usually do run it whenever the broken pipe problem appears to be on the "safe" side. But it seems to also work fine without it? Anyone has a clue?

Sometimes the PC would not boot and i needed to use a rescue image to rebuild the kernel and bootloader. Other times the PC booted just fine. I just manually run the `reinstall-kernels` script from EOS to ensure everything is fine.

**Comment by yogo1212** [comment]
@CaptainCoward the error message should be cosmetic only.

it is when kernel-install doesn't read the complete list of filenames *before it completes* that the message appears. therefore the process must have completed. other errors could happen, though. (there will likely be an indication of an error in the log, though)

@MartinX3 the process likely isn't deterministic. is the output stable if you run it manually?

**Comment by yogo1212** [comment]
@FlareFlo if that is the case, it might be another issue. are there any other error messages? because, as mentioned, the error should only appear once the hook has completed. `_alpm_hook_run_hook` also [checks the exit code and produces an error message when it's non-zero](https://gitlab.archlinux.org/pacman/pacman/-/blob/master/lib/libalpm/util.c#L785).

if it isn't urgent, let's see what happens once this issue is addressed. if the message persists and continues to correlate with inconsistent boot/efi partitions after the fix has been rolled out, we should take a closer look.

i can say with reasonable certainty that i only encounter messed up boot files - regardless of the error message - on my stationary computer when my small child presses the power button during an update. he's worked out the toggle on the power chord, the one on the power supply, and the power switch at the front. he just likes pressing buttons 🤷.

**Comment by Gotoro** [comment]
[The upstream is fixed](https://gitlab.com/dalto.8/kernel-install-for-dracut/-/issues/5#note_2977279288). I'm guessing we can close this now, if this doesn't cause any further issues for anybody. For me, as of 30.01.2026 I don't see the error any longer. Testing the [committed solution](https://gitlab.com/dalto.8/kernel-install-for-dracut/-/commit/20f005a3749996c8099a1d1397b2c58c584cc3ba) works.

**Comment by MartinX3** [comment]
I am not using `kernel-install-for-dracut` and still get it on my arch linux server with `dracut-110`.

```bash
:: Pre-transaction-Hooks werden gestartet …
(1/4) Ensure ESP is mounted...
(2/4) Removing initramfs with dracut
(3/4) Removing UKI images...
==> Removing /efi/EFI/Linux/linux-6.18.22-1-lts-ea4ba1ecc32e4c1a803fa9b6147573b1-rolling.efi...
Fehler: konnte nicht in Weiterleitung schreiben (Datenübergabe unterbrochen (broken pipe))
(4/4) Remove DKMS modules
```

```bash
:: Post-transaction-Hooks werden gestartet …
( 1/22) Creating system user accounts...
( 2/22) Creating temporary files...
( 3/22) Updating journal message catalog...
( 4/22) Updating udev hardware database...
( 5/22) Applying kernel sysctl settings...
( 6/22) Reloading system manager configuration...
( 7/22) Reloading user manager configuration...
( 8/22) Enqueuing marked services...
( 9/22) Reloading device manager configuration...
(10/22) Arming ConditionNeedsUpdate...
(11/22) Rebuilding certificate stores...
(12/22) Updating module dependencies...
(13/22) Install DKMS modules
==> depmod 6.18.23-1-lts
(14/22) Updating initramfs with dracut
--> Building initramfs for linux-lts (6.18.23-1-lts)
(15/22) Generating UKI images...
==> dracut-ukify -g linux-lts
  -> Building initrd image linux-lts (6.18.23-1-lts)
  -> Ukify image linux-lts (6.18.23-1-lts)
Wrote unsigned /efi/EFI/Linux/linux-6.18.23-1-lts-ea4ba1ecc32e4c1a803fa9b6147573b1-rolling.efi
Fehler: konnte nicht in Weiterleitung schreiben (Datenübergabe unterbrochen (broken pipe))
(16/22) Refreshing PackageKit...
(17/22) Gracefully upgrading systemd-boot...
(18/22) Backup ESP to other partition
(19/22) Reloading system bus configuration...
```

**Comment by yogo1212** [comment]
@MartinX3 it appears you're using dracut-ukify.

the issue could very well be something similar to what happened in the kernel-install wrapper. the handler for dracut-ukify must drain the entire input buffer before closing.

you can test by intercepting the list of changed files from a kernel update that libalpm/pacman sends and testing maybe like this:

```
cat "$extracted_file_list" | {
  dracut-ukify -z
  echo "=========== leftovers:"
  cat
}
```

**Comment by FlareFlo** [comment]
Not stale, still happens.

**Comment by yogo1212** [comment]
@FlareFlo can you please report in more details what still happens? the `Broken pipe` error or you having to rescue the system because it actually still bricks? or do you just run `reinstall-kernels` as a precaution when you see the message?

very likely, dracut is not causally involved in the error message showing up. the "unable to write to pipe" is emitted by pacman as a diagnostic for the hook. we need to figure out what isn't consuming the pipe to go after the error message. if your system goes into a broken state, we can try figuring that out as well.

the fix we talked about here is for `kernel-install-for-dracut` and landed in version `1.14.1`. i can see from your previous messages that you have `kernel-install-for-dracut` installed (since you're using `reinstall-kernels`). you're on EOS - i assume you didn't change the out-of-the-box configuration. is there anything else that could be important to know?

also, please post any terminal output with error information.

**Comment by FlareFlo** [comment]
> [@FlareFlo](https://github.com/FlareFlo) can you please report in more details what still happens? the `Broken pipe` error or you having to rescue the system because it actually still bricks? or do you just run `reinstall-kernels` as a precaution when you see the message?
> 
> very likely, dracut is not causally involved in the error message showing up. the "unable to write to pipe" is emitted by pacman as a diagnostic for the hook. we need to figure out what isn't consuming the pipe to go after the error message. if your system goes into a broken state, we can try figuring that out as well.
> 
> the fix we talked about here is for `kernel-install-for-dracut` and landed in version `1.14.1`. i can see from your previous messages that you have `kernel-install-for-dracut` installed (since you're using `reinstall-kernels`). you're on EOS - i assume you didn't change the out-of-the-box configuration. is there anything else that could be important to know?
> 
> also, please post any terminal output with error information.

I can post the error the next time it happens. Are there any verbose flags/specific logs i should attach?
