### ISSUE TITLE
dracut-install: weird behavior on Arch Linux

### ISSUE THREAD

**Issue by marcosfrm** [dracutdevs/dracut#333]
Arch has the following fs layout:

```
/
|-- bin -> usr/bin
|-- lib -> usr/lib
|-- lib64 -> usr/lib
|-- sbin -> usr/bin
|-- usr
|   |-- bin
|   |-- lib
|   |-- lib32
|   |-- lib64 -> lib
|   |-- sbin -> bin
```

Running

```
dracut-install -D test-dir -ldd -a mount
```

gives:

```
test-dir/
|-- bin -> usr/bin
|-- sbin -> usr/bin
`-- usr
    |-- bin
    |   `-- mount
    |-- lib
    |   |-- ld-2.26.so
    |   |-- ld-linux-x86-64.so.2 -> ../..//usr/lib/ld-2.26.so
    |   |-- libblkid.so -> ../..//usr/lib/libblkid.so.1.1.0
    |   |-- libblkid.so.1 -> ../..//usr/lib/libblkid.so.1.1.0
    |   |-- libblkid.so.1.1.0
    |   |-- libc-2.26.so
    |   |-- libc.so
    |   |-- libc.so.6 -> ../..//usr/lib/libc-2.26.so
    |   |-- libmount.so -> ../..//usr/lib/libmount.so.1.1.0
    |   |-- libmount.so.1 -> ../..//usr/lib/libmount.so.1.1.0
    |   |-- libmount.so.1.1.0
    |   |-- libpthread-2.26.so
    |   |-- libpthread.so
    |   |-- libpthread.so.0 -> ../..//usr/lib/libpthread-2.26.so
    |   |-- librt-2.26.so
    |   |-- librt.so -> ../..//usr/lib/librt-2.26.so
    |   |-- librt.so.1 -> ../..//usr/lib/librt-2.26.so
    |   |-- libuuid.so -> ../..//usr/lib/libuuid.so.1.3.0
    |   |-- libuuid.so.1 -> ../..//usr/lib/libuuid.so.1.3.0
    |   `-- libuuid.so.1.3.0
    |-- lib64 -> ..//usr/lib
    `-- sbin -> ..//usr/bin
```

`/lib` and `/lib64` symlinks are not created and inside `/usr` symlinks have double `/`.

dracut-046 here.

**Comment by marcosfrm** [comment]
And the original symlinks:

```
lrwxrwxrwx 1 root root 3 out 17 05:32 /usr/lib64 -> lib
lrwxrwxrwx 1 root root 3 out 17 05:32 /usr/sbin -> bin

-rwxr-xr-x 1 root root 176672 nov 28 09:32 /usr/lib/ld-2.26.so
lrwxrwxrwx 1 root root     10 nov 28 09:32 /usr/lib/ld-linux-x86-64.so.2 -> ld-2.26.so
lrwxrwxrwx 1 root root     17 out 31 14:47 /usr/lib/libblkid.so -> libblkid.so.1.1.0
lrwxrwxrwx 1 root root     17 out 31 14:47 /usr/lib/libblkid.so.1 -> libblkid.so.1.1.0
-rwxr-xr-x 1 root root 310040 out 31 14:47 /usr/lib/libblkid.so.1.1.0
```

**Comment by haraldh** [comment]
should be fixed with commit a13e97e5110121e38f9a6d9550b5ac07250a37af

**Comment by marcosfrm** [comment]
Thanks! Symlinks are fine now.

```
test-dir/
|-- bin -> usr/bin
|-- sbin -> usr/bin
`-- usr
    |-- bin
    |   `-- mount
    |-- lib
    |   |-- ld-2.26.so
    |   |-- ld-linux-x86-64.so.2 -> ld-2.26.so
    |   |-- libblkid.so -> libblkid.so.1.1.0
    |   |-- libblkid.so.1 -> libblkid.so.1.1.0
    |   |-- libblkid.so.1.1.0
    |   |-- libc-2.26.so
    |   |-- libc.so
    |   |-- libc.so.6 -> libc-2.26.so
    |   |-- libmount.so -> libmount.so.1.1.0
    |   |-- libmount.so.1 -> libmount.so.1.1.0
    |   |-- libmount.so.1.1.0
    |   |-- libpthread-2.26.so
    |   |-- libpthread.so
    |   |-- libpthread.so.0 -> libpthread-2.26.so
    |   |-- librt-2.26.so
    |   |-- librt.so -> librt-2.26.so
    |   |-- librt.so.1 -> librt-2.26.so
    |   |-- libuuid.so -> libuuid.so.1.3.0
    |   |-- libuuid.so.1 -> libuuid.so.1.3.0
    |   `-- libuuid.so.1.3.0
    |-- lib64 -> lib
    `-- sbin -> bin

```

`/lib` and `/lib64` symlinks are still not created, but I can do it  manually.
