### ISSUE TITLE
dracut.cmdline(7): document overlay persistence requirements

### ISSUE THREAD

**Issue by opk12** [dracutdevs/dracut#579]
`do_live_overlay()` in `dmsquash-live-root.sh` makes assumptions about persistence command-line arguments:

- rd.live.overlay's `pathspec` must start with /

because `devspec` is mounted on `/run/initramfs/overlayfs` and `pathspec` is expanded as `/run/initramfs/overlayfs$pathspec`. [source](https://github.com/dracutdevs/dracut/blob/RHEL-8/modules.d/90dmsquash-live/dmsquash-live-root.sh#L128)

- the overlay image must contain directories named overlayfs and ovlwork

[source](https://github.com/dracutdevs/dracut/blob/RHEL-8/modules.d/90dmsquash-live/dmsquash-live-root.sh#L145)

**Comment by ytrezq** [comment]
@opk12 : this is something I’m failing to understand.

What’s the directory structure for using persistant overlay alongside overlayfs ?

**Comment by FGrose** [comment]
`/run/overlayfs` is a symbolic link to `/run/initramfs/overlayfs/overlayfs`
and `/run/ovlwork` is a symbolic link to `/run/initramfs/overlayfs/ovlwork`

See https://github.com/dracutdevs/dracut/blob/2293609dcba01f5bf256b4245896927d4719a273/modules.d/90dmsquash-live/dmsquash-live-root.sh#L147

**Comment by johannbg** [comment]
This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by ytrezq** [comment]
@johannbg of course, this documentation problem should be solved. But I m not having much to add.

**Comment by opk12** [comment]
Reopening because the feature is unusable without knowledge of `ovlwork`. I'm not sure why this wasn't solved in 1 year?

**Comment by opk12** [comment]
Ciuld youj please reopen, as the feature is unusable without knowledge of `ovlwork` and the fix is a couple words?

**Comment by rustydb** [comment]
Definitely could use some documentation, I've been in a rabbit hole with this for some time. I make the overlay file, mount it, make the two directories... but I see blocks of logic that seem like i should make a directory instead of an overlay file.
Just some comments at a base level to tell which if block matters for which part of the doc would be amazing... Not trying to make a huge ask.

**Comment by opk12** [comment]
> This issue is being marked as stale because it has not had any recent activity. It will be closed if no further activity occurs. If this is still an issue in the latest release of Dracut and you would like to keep it open please comment on this issue within the next 7 days. Thank you for your contributions.

**Comment by johannbg** [comment]
.
