### ISSUE TITLE
ZSTD-compress kernel modules support?

### ISSUE THREAD

**Issue by xuanruiqi** [dracutdevs/dracut#945]
**Describe the bug**
Recently I tried to move to ZSTD for kernel compression, but it seems that Dracut is not very happy. It claims that it "can't find" the desired modules in the compressed `.ko.zst` files.

**Distribution used**
Arch Linux

**Dracut version**
050

**Init system**
systemd

**To Reproduce**

    dracut -v -f --no-hostonly-cmdline /boot/initramfs-xanmod.img --kver 5.8.15-xanmod1-1

**Expected behavior**
Dracut finds all required modules and builds them into the initramfs.

**Comment by xuanruiqi** [comment]
Rebuilding the kernel with XZ module compression does work, so I suppose it's a ZSTD support problem.

**Comment by xuanruiqi** [comment]
This might not be a bug, more of documentation/feature...

**Comment by danimo** [comment]
Good idea indeed. Can you test the patch in the referenced PR?

**Comment by xuanruiqi** [comment]
Thanks; it would take some time (I'd have to build the PR'd dracut and rebuild my kernel with ZSTD-compressed modules). But I'd love to try it out!

**Comment by xuanruiqi** [comment]
Not working: it seems you've been hardcoding the extensions in the file, but `.zst` is more frequently used as an extension for ZSTD-compressed files (and kernel modules) than `.zstd`.

**Comment by xuanruiqi** [comment]
OK, the issue seems beyond that... I hand-patched the code to add the extension `.zst` and it was still not working.

**Comment by danimo** [comment]
I have updated the patch. This works for me.

**Comment by xuanruiqi** [comment]
Haven't had the chance to try again, let me try...

**Comment by xuanruiqi** [comment]
Still not working for me:

    dracut-install: Failed to find module 'pinctrl_amd' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/pinctrl/pinctrl-amd.ko.zst
    dracut-install: Failed to find module 'usbhid' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/usbhid/usbhid.ko.zst
    dracut-install: Failed to find module 'hid_generic' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-generic.ko.zst
    dracut-install: Failed to find module 'hid_lg_g15' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-lg-g15.ko.zst
    dracut-install: Failed to find module 'hid_logitech_dj' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech-dj.ko.zst
    dracut-install: Failed to find module 'hid_logitech_hidpp' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech-hidpp.ko.zst
    dracut-install: Failed to find module 'hid_logitech' /lib/modules/5.9.2-xanmod1-1//kernel/drivers/hid/hid-logitech.ko.zst

**Comment by danimo** [comment]
@xuanruiqi which kernel starts to support zstd btw?

**Comment by xuanruiqi** [comment]
You need to have a patched kernel; it isn't in the mainline yet. Xanmod for example provides this patch.

**Comment by xuanruiqi** [comment]
This is not stale as AFAIK it is not fixed yet

**Comment by Atemu** [comment]
Are you sure it supports zstd-compressed *modules*? The mainline kernel supports zstd for the kernel image and initrd but not for modules for example.

**Comment by xuanruiqi** [comment]
Yes, at least Xanmod supports it. AFAIK, probably a few patchsets do. Since dracut was supporting ZSTD-compressed kernel images way before it went official, it might be a good idea to support this ahead of mainline.

**Comment by sirlucjan** [comment]
As much as possible you can use modules compressed in .zst format - I use such a solution myself, but using patched mkinitcpio. The problem is probably kmod - only yesterday released version 28 allows you to handle modules compressed in zstd format without any problems. Use the new kmod and it should work.

**Comment by xuanruiqi** [comment]
Since @danimo's fix cannot break existing features, I would really appreciate if this could get merged soon! And then I could see if with the latest `kmod` I could get everything to work...

**Comment by johannbg** [comment]
This seems to have been resolved with the 28 release of kmod hence closing.
